#server:
#  port: 8080
#  servlet:
#    context-path: /web

# 数据库相关配置
spring:
  datasource:
    # 数据库访问配置, 使用druid数据源 com.alibaba.druid.pool.DruidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.138.222:3306/dxyl_pumian?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: dxyl123456
    druid:
      # 连接池配置 初始化大小、最小、最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 测试连接
      validation-query: select 1 from dual
      # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      # 获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      # 归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      # 是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      # 开启poolPreparedStatements后生效
      max-pool-prepared-statement-per-connection-size: 20
      # 配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: admin
        login-password: admin123
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218
      # 配置日志输出
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false

# 日志配置文件路径
logging:
  config: classpath:log4j2.xml
  level:
    root: debug

# MyBatis
mybatis:
  # entity扫描的包名
  type-aliases-package: com.zuji.mapper
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  # 配置文件的路径
  config-location: classpath:/config/mybatis-config.xml
  # 检查配置文件是否存在
  check-config-location: true
  # 设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE
  executor-type: simple
  # 扫描typeHandlers的包
#  type-handlers-package:

# 分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
  offset-as-page-num: true
  row-bounds-with-count: true



